### ISSUE TITLE
mysql_driver.py method name misspeled ?!

### ISSUE THREAD

**Issue by 010ric** [hsadler/flask-vue-project-seed#1]
As I was going to try out this nice full stack architecture there occourred an error while initializing the front end server using the table creation python script ("cd /app/server/scripts/ && python3 create-wall-message-table.py"). 

I need permission to commit the changes, so while missing these I wanted to give you my feedback and code changes using the issue section.

file app/server/scripts/create-wall-message-table.py in line 23
--------------------------------------------------------------------------------

 		attribution VARCHAR(255)
 	)
 """
-query_result = mysql_driver.query(query_string=create_table_query)
+query_result = mysql_driver.query_bind(query_string=create_table_query)
 
 ppp('result of create table query:', query_result)
--------------------------------------------------------------------------------

Greetings from Munich
Mario

**Comment by hsadler** [comment]
Sorry for the late response. I haven't been keeping up with this repo. Can you cut a branch and submit a pull request?

**Comment by 010ric** [comment]
Yes sure I will do so in the next days.

**Comment by 010ric** [comment]
Seems like I had am mistake in my source code as the change I proposed would be:

replace  " query_result = mysql_driver.query(query_string=create_table_query) " with " query_result = mysql_driver.query_bind(query_string=create_table_query) ". Which holds already for the source code in your repo.
